import Image1 from "./img-svg/8498d4a75cc90ab1d7a8e7dbd8a57fe1.png"
export const ItemsData = [
  {
    id         : 1,
    projectName: "Project name 1",
    descH      : "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. ",
    skills     : ["Landing", "Development"],
    description: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    concept: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    tasks: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    result: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    img: [Image1]
  },
  {
    id         : 2,
    projectName: "Project name 2",
    descH      : "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. ",
    skills     : ["Landing", "Development", "BackEnd", "Optimization"],
    description: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    concept: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    tasks: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    result: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    img: [Image1]
  },
  {
    id         : 3,
    projectName: "Project name 3",
    descH      : "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. ",
    skills     : ["Landing", "Development"],
    description: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    concept: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    tasks: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    result: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    img: [Image1]
  },
  {
    id         : 4,
    projectName: "Project name 4",
    descH      : "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. ",
    skills     : ["Landing", "Development"],
    description: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    concept: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    tasks: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    result: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    img: [Image1]
  },
  {
    id         : 5,
    projectName: "Project name 5",
    descH      : "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. ",
    skills     : ["Landing", "Development"],
    description: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    concept: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    tasks: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    result: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    img: [Image1]
  },
  {
    id         : 6,
    projectName: "Project name 6",
    descH      : "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. ",
    skills     : ["Landing", "Development"],
    description: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    concept: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    tasks: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    result: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    img: [Image1]
  },
  {
    id         : 7,
    projectName: "Project name 7",
    descH      : "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. ",
    skills     : ["Landing", "Development"],
    description: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    concept: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    tasks: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    result: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    img: [Image1]
  },
  {
    id         : 8,
    projectName: "Project name 8",
    descH      : "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. ",
    skills     : ["Landing", "Development"],
    description: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    concept: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    tasks: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    result: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    img: [Image1]
  },
  {
    id         : 9,
    projectName: "Project name 9",
    descH      : "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. ",
    skills     : ["Landing", "Development"],
    description: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    concept: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    tasks: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    result: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    img: [Image1]
  },
  {
    id         : 10,
    projectName: "Project name 10",
    descH      : "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. ",
    skills     : ["Landing", "Development"],
    description: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    concept: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    tasks: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    result: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    img: [Image1]
  },
  {
    id         : 11,
    projectName: "Project name 11",
    descH      : "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. ",
    skills     : ["Landing", "Development"],
    description: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    concept: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    tasks: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    result: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    img: [Image1]
  },
  {
    id         : 12,
    projectName: "Project name 12",
    descH      : "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. ",
    skills     : ["Landing", "Development"],
    description: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    concept: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    tasks: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    result: "Manual entry and processing of data can lead to errors that can be both time-consuming and costly. Automating processes and data capture can help eliminate these issues and increase accuracy. With our business expertise and our industry leading DAP technology, we are helping transform any company to compete in today's business environment. Boost Software's solutions span the major platforms driving today's enterprise businesses including: SAP (Successfactors, Concur, S/4HANA), Workday, Oracle, Salesforce, and major CRM and HCM platforms.",
    img: [Image1]
  },
];